services:
  postgres:
    image: postgres:15
    networks:
      - aim-trainer
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    image: 172.16.0.100:8011/aim-trainer-server
    networks:
      - aim-trainer
    ports:
      - '8062:3000'
    environment:
      - PORT
      - DB_HOST
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
    depends_on:
      - postgres

  client:
    image: 172.16.0.100:8011/aim-trainer-client
    networks:
      - aim-trainer
    ports:
      - '8061:4173'
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - server

volumes:
  postgres_data:
networks:
  aim-trainer:
